
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ticket_booking
    username: root
    password: 12123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
#        generate_statistics: true
        hbm2ddl:
          auto: none
    show-sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false

    #    spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false